Add missing word "requiring"
steveklabnik/jujutsu-tutorial pull request #43
Opened 2024-10-20 13:49 UTC by ryecroft

Or insisting/mandating/needing

2024-10-21 00:08 UTC, steveklabnik requested changes

2024-10-21 00:08 UTC, steveklabnik commented on src/introduction/what-is-jj-and-why-should-i-care.md
> +else you're working with convert too. This means that there's no real
adding requiring is good, but we also need to not remove this too

2024-10-21 08:41 UTC, ryecroft reviewed
Sounds good 👍

2024-10-24 00:30 UTC, steveklabnik commented on src/introduction/what-is-jj-and-why-should-i-care.md
> +else you're working with convert too. This means that there's no real
```suggestion
else you're working with convert to. This means that there's no real
```

2024-10-24 00:31 UTC, steveklabnik approved these changes
Thanks!

2024-10-24 00:31 UTC, merged